#%RAML 1.0 DataType
displayName: Account
description: Defines the fields in Account Datatype

type: object
properties:
  customerID: integer
  fName: string
  lName: string
  phoneNumber: string
  SSN: string
  customerAddress: string
